# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7f0d8efe31bb66777f6ab9317668433faabfc0e87d680389e91713a46af5edeecc2b9e2659d84cae00e75906a79c8b229c8c1d823202d1f7531ef09d638f739

test:
  secret_key_base: fedf2713351548d5b5d0e796d5433899b36832fd047c2ab69cdf05b03053a15499aa0a980922ff4ed3369ba9e881a24e81ab1ddbb6e7487ec51baec97522e3ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
